name: 'Setup Tests'
description: 'Set up pnpm, node w/ pnpm cache, install and audit deps, compile, and restore electron cache'
inputs:
  cache-key:
    description: 'The key to the electron cache'
    required: true
  cache-path:
    description: 'The path to the electron cache'
    required: true
  version:
    description: 'The pnpm version to use'
    required: false
    default: 7.13.2

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
      with:
        version: ${{ inputs.version }}

    - name: Setup node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
      with:
        node-version: '14'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Compile
      run: pnpm compile
      shell: bash
    
    - name: Cache Electron
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

## Usage
# - name: Setup Tests
#   uses: ./.github/actions/pretest
#   with:
#     cache-path: ~/Library/Caches/electron
#     cache-key: v-11.0.0-macos-electron