name: Docker Deployment

on:
  # release: 
  #   types: [published] 
 push:
   tags:
     - docker*

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      
      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all Docker images
        run: sh ./docker/build.sh

      - name: Push all Docker images
        run: sh ./docker/push.sh
