name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read  # for github/issue-labeler to get repo contents
      issues: write  # for github/issue-labeler to create or remove labels
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@829a8bf1b184f74cc575b5435093a92c7b846983 # tag=v2.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/issue-labeler.yml
        enable-versioned-regex: 0
        