on: issues
name: Create Default Labels
permissions: {}
jobs:
  labels:
    permissions:
      contents: read # to fetch code (actions/checkout)
      issues: write # to add label to issues 

    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - uses: lannonbr/issue-label-manager-action@7890981d0e8f2922211a7fe2c391c53cb3037cb4 # tag=3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: false # will delete any labels that aren't in the .github/labels.json (this is set to false by default)
